---
# IOS provider for doing config backup
#

- name: set extensions if present
  set_fact: ext="{{ backup_config.extensions }}"
  when: backup_config.extensions is defined

- name: Backup Device config to specified location
  config_backup:
    path: "{{ backup_config.path }}"
    filename: "{{ backup_config.filename }}"
    extensions: "{{ ext }}"
  when: ext is defined

- name: End the play
  meta: end_play
  when: ext is defined

- name: Backup Device config to specified location
  config_backup:
    path: "{{ backup_config.path }}"
    filename: "{{ backup_config.filename }}"
